//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordReplacer.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordReplacer.UI.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string btnRemoveAll {
            get {
                return ResourceManager.GetString("btnRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace and Download.
        /// </summary>
        public static string btnReplaceTextDefault {
            get {
                return ResourceManager.GetString("btnReplaceTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, replacing....
        /// </summary>
        public static string btnReplaceTextReplacing {
            get {
                return ResourceManager.GetString("btnReplaceTextReplacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Text.
        /// </summary>
        public static string buttonTextAddValues {
            get {
                return ResourceManager.GetString("buttonTextAddValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file and add some text to begin the replacement.
        /// </summary>
        public static string emptyValueListInfo {
            get {
                return ResourceManager.GetString("emptyValueListInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to replace a text with an empty replacement List. To do this, use a Text option..
        /// </summary>
        public static string errorListEmptyToBeReplaced {
            get {
                return ResourceManager.GetString("errorListEmptyToBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer text.
        /// </summary>
        public static string headerNewValues {
            get {
                return ResourceManager.GetString("headerNewValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        public static string headerOriginalValues {
            get {
                return ResourceManager.GetString("headerOriginalValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text that will be replaced.
        /// </summary>
        public static string helperTextAddValues {
            get {
                return ResourceManager.GetString("helperTextAddValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site may freeze during the replacement process. Please just wait..
        /// </summary>
        public static string InfoSiteFreezes {
            get {
                return ResourceManager.GetString("InfoSiteFreezes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple words/phrases.
        /// </summary>
        public static string inputTypeList {
            get {
                return ResourceManager.GetString("inputTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will replace &quot;{0}&quot; for multiple words (generate multiple files).
        /// </summary>
        public static string inputTypeListLabel {
            get {
                return ResourceManager.GetString("inputTypeListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single word/phrase.
        /// </summary>
        public static string inputTypeText {
            get {
                return ResourceManager.GetString("inputTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will replace &quot;{0}&quot; for another word.
        /// </summary>
        public static string inputTypeTextLabel {
            get {
                return ResourceManager.GetString("inputTypeTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be replaced.
        /// </summary>
        public static string labelTextAddValues {
            get {
                return ResourceManager.GetString("labelTextAddValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is will be the new text.
        /// </summary>
        public static string newDocumentHelperText {
            get {
                return ResourceManager.GetString("newDocumentHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value for &quot;{0}&quot;.
        /// </summary>
        public static string newDocumentLabel {
            get {
                return ResourceManager.GetString("newDocumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the original text.
        /// </summary>
        public static string originalDocumentHelperText {
            get {
                return ResourceManager.GetString("originalDocumentHelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original text.
        /// </summary>
        public static string originalDocumentLabel {
            get {
                return ResourceManager.GetString("originalDocumentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Presets:.
        /// </summary>
        public static string presetLabel {
            get {
                return ResourceManager.GetString("presetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can save some presets, with original and newer values, to replace it later. This preset will ONLY BE SAVED in your BROWSER..
        /// </summary>
        public static string presetToolTip {
            get {
                return ResourceManager.GetString("presetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this word.
        /// </summary>
        public static string thisWordDefaultValue {
            get {
                return ResourceManager.GetString("thisWordDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again..
        /// </summary>
        public static string toasterGenericError {
            get {
                return ResourceManager.GetString("toasterGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word/text {0} has already been added..
        /// </summary>
        public static string valueAlreadyAddedError {
            get {
                return ResourceManager.GetString("valueAlreadyAddedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate original text.
        /// </summary>
        public static string valueAlreadyAddedErrorTitle {
            get {
                return ResourceManager.GetString("valueAlreadyAddedErrorTitle", resourceCulture);
            }
        }
    }
}
